In [1]:
import pandas as pd
from datasets import load_dataset

## empathetic_dialogues

In [10]:
empathetic_dialogues = load_dataset("empathetic_dialogues",trust_remote_code=True)
print("1")
print(empathetic_dialogues)

Downloading readme: 0.00B [00:00, ?B/s]

1
DatasetDict({
    train: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 76673
    })
    validation: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 12030
    })
    test: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 10943
    })
})

In [7]:
empathetic_dialogues

DatasetDict({
    train: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 76673
    })
    validation: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 12030
    })
    test: Dataset({
        features: ['conv_id', 'utterance_idx', 'context', 'prompt', 'speaker_idx', 'utterance', 'selfeval', 'tags'],
        num_rows: 10943
    })
})

In [5]:

rows = []

for item in empathetic_dialogues["train"]:
    rows.append({
        "dataset": "empathetic_dialogues",
        "conversation_id": item["conv_id"],
        "role": "user" if item["speaker_idx"] == 0 else "assistant",
        "text": item["utterance"],
        "emotion": item["context"]
    })

df_empathetic = pd.DataFrame(rows)
# df_empathetic.to_csv("empathetic_dialogues.csv", index=False)
df_empathetic_train

,dataset,conversation_id,role,text,emotion
0,empathetic_dialogues,hit:0_conv:1,assistant,I remember going to see the fireworks with my ...,sentimental
1,empathetic_dialogues,hit:0_conv:1,user,Was this a friend you were in love with_comma_...,sentimental
2,empathetic_dialogues,hit:0_conv:1,assistant,This was a best friend. I miss her.,sentimental
3,empathetic_dialogues,hit:0_conv:1,user,Where has she gone?,sentimental
4,empathetic_dialogues,hit:0_conv:1,assistant,We no longer talk.,sentimental
...,...,...,...,...,...
76668,empathetic_dialogues,hit:12424_conv:24848,assistant,Yeah reminds me of the good old days. I miss ...,sentimental
76669,empathetic_dialogues,hit:12424_conv:24849,assistant,I woke up this morning to my wife telling me s...,surprised
76670,empathetic_dialogues,hit:12424_conv:24849,assistant,Oh hey that's awesome! That is awesome right?,surprised
76671,empathetic_dialogues,hit:12424_conv:24849,assistant,It is soooo awesome. We have been wanting a b...,surprised
76672,empathetic_dialogues,hit:12424_conv:24849,assistant,That is awesome!!!! Congratulations!,surprised

## Daily_dialog

In [13]:
daily_dialog = load_dataset("roskoN/dailydialog",trust_remote_code=True,download_mode="force_redownload")
print("2")
print(daily_dialog)

Downloading data: 100%|████████████████████| 3.67M/3.67M [00:00<00:00, 4.75MB/s]
Downloading data: 100%|██████████████████████| 340k/340k [00:00<00:00, 1.14MB/s]
Downloading data: 100%|██████████████████████| 337k/337k [00:00<00:00, 1.33MB/s]

Generating train split:   0%|          | 0/11118 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

2
DatasetDict({
    train: Dataset({
        features: ['id', 'acts', 'emotions', 'utterances'],
        num_rows: 11118
    })
    validation: Dataset({
        features: ['id', 'acts', 'emotions', 'utterances'],
        num_rows: 1000
    })
    test: Dataset({
        features: ['id', 'acts', 'emotions', 'utterances'],
        num_rows: 1000
    })
})

In [19]:
print(daily_dialog['train'][0])

{'id': 'a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77f87e5f41290ff61c3d_0', 'acts': [3, 4, 2, 2, 2, 3, 4, 1, 3, 4], 'emotions': [0, 0, 0, 0, 0, 0, 4, 4, 4, 4], 'utterances': ['Say , Jim , how about going for a few beers after dinner ?', 'You know that is tempting but is really not good for our fitness .', 'What do you mean ? It will help us to relax .', "Do you really think so ? I don't . It will just make us fat and act silly . Remember last time ?", "I guess you are right.But what shall we do ? I don't feel like sitting at home .", 'I suggest a walk over to the gym where we can play singsong and meet some of our friends .', "That's a good idea . I hear Mary and Sally often go there to play pingpong.Perhaps we can make a foursome with them .", 'Sounds great to me ! If they are willing , we could ask them to go dancing with us.That is excellent exercise and fun , too .', "Good.Let ' s go now .", 'All right .']}

In [20]:
rows = []

for idx, item in enumerate(daily_dialog["train"]):
        rows.append({
            "dataset": "daily_dialog",
            "conversation_id": item['id'],
            "acts": item['acts'],
            "text": item['utterances'],
            "emotion": item["emotions"]
        })

df_daily = pd.DataFrame(rows)
df_daily
# df_daily.to_csv("daily_dialog.csv", index=False)

,dataset,conversation_id,acts,text,emotion
0,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[3, 4, 2, 2, 2, 3, 4, 1, 3, 4]","[Say , Jim , how about going for a few beers a...","[0, 0, 0, 0, 0, 0, 4, 4, 4, 4]"
1,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[2, 1, 2, 2, 1, 1]","[Can you do push-ups ?, Of course I can . It's...","[0, 0, 6, 0, 0, 0]"
2,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[2, 1, 2, 1, 1]","[Can you study with the radio on ?, No , I lis...","[0, 0, 0, 0, 0]"
3,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[2, 1, 1, 1]","[Are you all right ?, I will be all right soon...","[0, 0, 0, 0]"
4,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[2, 1, 2, 1, 1, 2, 1, 3, 4]","[Hey John , nice skates . Are they new ?, Yeah...","[0, 0, 0, 0, 0, 6, 0, 6, 0]"
...,...,...,...,...,...
11113,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[1, 1, 1, 2, 3, 2, 1, 4, 1]","[Hello , I bought a pen in your shop just befo...","[0, 4, 0, 0, 0, 0, 0, 0, 4]"
11114,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[2, 1, 2, 1, 3, 4]","[Do you have any seats available ?, Yes . This...","[0, 0, 0, 0, 0, 4]"
11115,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 3, 4]","[Uncle Ben , how did the Forbidden City get th...","[0, 0, 6, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0]"
11116,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[2, 3, 4, 3]","[May I help you , sir ?, I want a pair of locu...","[0, 0, 0, 0]"
11117,daily_dialog,a438b751ab9997cdb35f07bfe3dfb010b96365f4762d77...,"[3, 4]","[Could I have the check , please ?, Okay . I'l...","[0, 0]"

## GoEmotions

In [22]:
go_emotions = load_dataset("go_emotions",trust_remote_code=True)
print("3")
print(go_emotions)

Downloading readme: 0.00B [00:00, ?B/s]

3
DatasetDict({
    train: Dataset({
        features: ['text', 'labels', 'id'],
        num_rows: 43410
    })
    validation: Dataset({
        features: ['text', 'labels', 'id'],
        num_rows: 5426
    })
    test: Dataset({
        features: ['text', 'labels', 'id'],
        num_rows: 5427
    })
})

In [23]:
print(go_emotions["train"][0])

{'text': "My favourite food is anything I didn't have to cook myself.", 'labels': [27], 'id': 'eebbqej'}

In [24]:
rows = []

for idx, item in enumerate(go_emotions["train"]):
    rows.append({
        "dataset": "go_emotions",
        "conversation_id": idx,
        "role": "user",
        "text": item["text"],
        "emotion": item["labels"]  # 這是 list，需要之後轉換
    })

df_go = pd.DataFrame(rows)
df_go
# df_go.to_csv("go_emotions.csv", index=False)

,dataset,conversation_id,role,text,emotion
0,go_emotions,0,user,My favourite food is anything I didn't have to...,[27]
1,go_emotions,1,user,"Now if he does off himself, everyone will thin...",[27]
2,go_emotions,2,user,WHY THE FUCK IS BAYLESS ISOING,[2]
3,go_emotions,3,user,To make her feel threatened,[14]
4,go_emotions,4,user,Dirty Southern Wankers,[3]
...,...,...,...,...,...
43405,go_emotions,43405,user,Added you mate well I’ve just got the bow and ...,[18]
43406,go_emotions,43406,user,Always thought that was funny but is it a refe...,[6]
43407,go_emotions,43407,user,What are you talking about? Anything bad that ...,[3]
43408,go_emotions,43408,user,"More like a baptism, with sexy results!",[13]
43409,go_emotions,43409,user,Enjoy the ride!,[17]